import React from 'react';
import {
  Accordion,
  AccordionItem,
  AccordionItemHeading,
  AccordionItemButton,
  AccordionItemPanel,
} from 'react-accessible-accordion';
import '../Styling/blogs.css';
import AnimateWriting from './AnimateWriting';
import WorldRoute from '../Assets/worldmap.png';

function RTWBlog() {

  const writingSequence = ['30,000km Around The World', 1000]

  return (
    <div className='main-container'>
      <div className='title'>
        <AnimateWriting writingSequence={writingSequence} />
      </div>
      <div className='route'>
        <img className='route-image' src={WorldRoute} alt="LEJOG Route" />
      </div>
      <br></br>
      <div><h2>Preparation</h2></div>
      <Accordion allowZeroExpanded>
        <AccordionItem>
          <AccordionItemHeading>
            <AccordionItemButton>
              15/3/2016 First blog ahoy
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Mike</p>
            <p>It's March 2016 and this is our first (of hopefully many) blog posts, both in preparation for the trip and from the road.  We're hoping to keep this updated regularly with all sorts of aspects of our trip and our lives, so people get a really good idea of who we are, why we're doing this, and what's it's really like for two people to quit their jobs, pack up, and cycle around the world together.</p>
            <p>We're a product of internet dating, so hopefully that makes for an interesting start already… In truth, before we met, we were independently thinking about riding around the world solo, and it just so happened that we found in each other another person equally crazy enough to want to do it (and to do it together).  But cycling and that ambition isn't the only thing we've got in common; we share an outlook on most aspects of life (except on the Cadbury/Galaxy chocolate debate, what constitutes 'a nice temperature' and vegetarianism [Helen's note: Galaxy and 'not so cold you shiver']).  We both know that there's more to life than a house, car and career, and since there was nothing stopping us except ourselves fulfilling a long held dream, why not actually go and do it?</p>
            <p>Mental health is something that is very important to us both.  We’ve both suffered through difficult times in our lives, and seen those times out.  Many people aren’t so lucky.  Many people don’t have a network of supportive friends, family and colleagues with the patience, empathy and understanding to help.  Many people view mental ill health as something to be ashamed of,  or to be scared of, or simply as a weakness.  It affects so many people, and really it's none of those things; it’s an illness and it’s treatable.  And therein lies the rub: sufferers often lack support and understanding, or fear opening up about being unwell.  In our view that is among the most damaging aspects; it causes sufferers to internalise their illness, doubt and blame themselves, it destroys their wellbeing, they withdraw and repeat: a process that can be crippling iterative. We don’t have the answer but what we do know is that, from our experience, openness and support helps a great deal. </p>
            <p>So, when we speak about ‘raising awareness of mental ill health’ we address it to two audiences. Firstly, to those lucky enough not to experience it, it’s just like any other illness: a simple misfortune, so don’t assign blame to the sufferer, they aren’t weak or at fault.  What’s more, you probably know someone who isn’t well. The signs aren’t always obvious: a friend might be ignoring your texts, or drinking too much, or glossing over something that ought to be difficult for them: stoicism and smiling is the classic mask of the depressed mind. So be observant, be thoughtful, ask uncomfortable questions and be willing to offer support (for which you might not always receive immediate thanks).  If they open up to you, be grateful: you’re trusted and special, albeit you may feel you’ve received a difficult privilege.  And to the sufferers, the message is the same: don’t be embarrassed or ashamed; it’s ok not to be well. Find someone you can talk to, trust that there are people who want to and are able to help.  Even if you just speak to your doctor at first, take that daunting step. It’s the first on the path to wellness, and there will be people to help you along the way.  Think of them as sherpas, if you want, and unburden yourself just a little.</p>
            <p>So our thanks go out our friends, family and colleagues who guided us to better times, and our thoughts to those who need the support of those around them.</p>
            <p>And so here’s to the path to wellness, a route that is taking us Ever East.</p>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionItemHeading>
            <AccordionItemButton>
              19/5/2016 Bikes go around the world
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Mike</p>
            <p>Golly there are a lot of bikes.  A lot of bloggers will say that any old bike will get you round the world.  To be fair that's probably right, but with visas, wild camping, water, weather and money to worry about as we go, I can't face the prospect of being stranded if the bike can't manage the journey! So, shiny new bikes are the order of the day for me and old Clarkingtons [2022 note: that's me, Helen, he's referring to]</p>
            <p>We spent A LOT of time researching bikes that were available off the shelf, looking at the spec list for each and trying to figure out if the componentry was up to the job, and whether, if anything went wrong we could fix it or find spares in the remoter parts. After looking at some fantasy bikes (from Thorn and Koga, lovely but too expensive) and ones within our budget of around £1,500, including panniers and the rest (like the Kona Sutra, or the Specialized Awol, or Cinelli Hobootleg ), I came to the conclusion that speccing our own from the components up might just be answer.  On the bikes we could afford there were certain parts that I just couldn't get comfortable with… like sub-par wheels, or STI shifters.  The chance that these could fail was just too much, however unlikely that actually is.  Even mechanical issues in Scotland have been an issue in the past, so in needed to get the failure risk as low as possible.</p>
            <p>So the grand trawl had to begin.  It started with taking a standard long haul trucker and going through the components.  In a few hours I figured that with some selective shopping we could put together bikes built of better parts, for the same cash. By better I don't mean more expensive, I mean more suitable.  Hood brakes on good cantilevers with bar end shifters, stronger wheels, stronger racks, a better seatpost. The focus of the exercise was on reliability, then fixablility, then replaceablity.  With so many hours researching comes another advantage - I actually understand nearly every aspect of the bikes we are going to ride round the world.  And that's the second tick for building our own, because Helen and I are putting the bikes together with our own hands (and the hands of a friendly man called Dan) we should, in theory, be better placed to make the repairs we need on the road.</p>
            <p>A full component list is going to follow once the bikes are built, together with a full breakdown of costs and our assembly, but to start with we've spent under £1,000 each so far, including frames, Tubus racks, Vaude panniers, and having carbide rimmed dyno hub wheels hand built by top man Harry Rowland. And there's really not that much left to get.  By my reckoning the complete bikes will be coming in at about £1,500 a piece, including all the extras.  So if you're interested, check back to see them in their final form, meanwhile, I need to get my credit card out and back to google - our first test tour is coming up in July.</p>
            <p>Oh and as an added bonus - Gareth at spray.bike is very generously letting us have some of his brilliant paint so we can customise the bikes even more.  Thanks Gareth! </p>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionItemHeading>
            <AccordionItemButton>
              6/7/2016 An introduction to our bikes
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Mike</p>
            <p>So, it’s about time I wrote something a little more about the building of our bikes. To begin with we should probably explain that we’ve built the bikes on the three Rs: reliability, repairability, replacability. They are built so that if they fail (which they shouldn’t) we can fix them, and if we can’t fix them we should be able to buy the parts we need literallyanywhere on earth. In short, they are very simple bikes and very high quality. So the parts in particular are:</p>
            <p><strong>The Frame</strong>
              <br></br>We bought Surly Long Haul Trucker frames, fairly cheap online. They cost £318.74 a piece which is about as cheap as you can get them. There’s no glamour, they’re just strong, simple and comfortable.</p>
            <p><strong>Wheels</strong>
              <br></br>Unlike the frame, the wheels are something a bit special. We enlisted the services of famed wheel builder Harry Rowland from lovely Kent, where Helen comes from. The rims are from the Netherlands, from a company called Ryde. They are Ryde’s Sputnik rim supersonically coated with tungsten carbide. This means that, although they need special brake blocks, the rims should make it 26,000 miles around the world. Spokes on both are a selection of decent spam, recommend by Harry Rowland. The rear hub is a bog standard cup-and-cone Deore LX that we can service as we go. The front hub is a Son Schmidt 28 dyno-hub that should be good for 50,000 km. These are wrapped in 2 inch Schwalbe Marathon Supremes that roll quickly but are still comfortable.</p>
            <p><strong>Drivetrain</strong>The drivetrain is based around the Deore XT range from Shimano with Deore XT front and rear derailleurs. On the rear is a 11-34 cassette (a fairly standard Shimano HG80) and the crankset is Spa Cycles own XD2, based on the classic Sugino crankset, but an awful lot cheaper. I expect that before we go we will have to replace the chain rings with something a little more fancy so that they can last the course. Connecting front and rear is a KMC X9 chain, the strongest we could get.</p>
            <p><strong>Cockpit</strong>
              <br></br>I decided to go for the Nitto Noodle handlebars, because nobody recommended anything else. These are wrapped in lovely squishy Specialized Bar Phat. At the ends are basic Diacompe bar end friction shifters that should work with any drivetrain that we later need to install. For the hoods, we chose a basic Tiagra aero brake lever.</p>
            <p><strong>Stopping</strong>
              <br></br>Because the rims are carbide coated, they are extremely aggressive towards brake pads. We chose Avid’s Shorty 4 cantilever brakes because they can take V-brake pads, with which we are running Swisstop Blue pads. Initially, we had Koolstop black pads which were supposed to match with the carbide rims, however they more or less dissolved after 60 miles. Apparently Koolstop are in production of an updated pad that will be able to cope with Ryde’s new carbide formula.</p>
            <p><strong>Luggage</strong>
              <br></br>We bought Tubus racks. It’s because they’re the best. We are taking with us Vaude panniers, the choice was really only between Vaude and Ortlieb but we could get the Vaude Aqua range for about half the price of the Ortliebs, and when we looked into it they seemed to be more adaptable and a better fit for the bikes.  We still need to buy our handlebar bags, but they’re not particularly urgent for now (and we know we’ll be buying Vaude ones anyway). [post-ride edit: these Vaude bags are atrocious, we ended up replacing all our bags with Ortlieb in Bulgaria]</p>
            <p><strong>Saddles</strong>
              <br></br>I went for my trusty old Rido Sport R2 (that took me down the West Coast of America), Helen plumped for a Brooks saddle yet to be broken in. These are mounted on Suntour SP12-NCX suspension seat posts to soak up all of the rough stuff.</p>
            <p><strong>Bits and bobs</strong>
              <br></br>Apart from all of the above, the rest of pretty basic and standard, which is the point. Nice and simple Shimano mountain bike cables, a fairly basic alloy stem, a square taper bottom bracket and some alloy spacers. None of those things should really break, but if they do it’s an easy fix or replacement.  And mud guards (SKS Bluemels). Because it’s nice to be dry.</p>
            <p><strong>Power</strong>
              <br></br>The front hub, the Schmidt Son 28, is powering our Sinewave Reactor USB ports which are a super simple top cap replacement with a little gold plated USB socket, to endure all weathers. Together, the hub and reactor convert the forward motion of the bike to a steady electrical output that we can use to charge all of our gizmos and gadgets as we go so we can keep updated all the way.</p>
            <p><strong>Fankly bits</strong>
              <br></br>These are the bits I didn’t account for despite all of my hours of research. In truth, there were only really two:
              <br></br>1. The hanger on the stem for the calliper brake cable
              <br></br>2. This was the big one: the cable guides for front and rear derailleur.
              <br></br>I had no idea that the Long Haul Trucker frame didn’t come with cable guides, and in fact looked like it was more suited for down tube shifters. Of course, there are cable guides separately available, but not on a Sunday in Glasgow when no one knows what you’re talking about and you really, really want to get the bikes finished.  So, if you watch our little video, you will see that we went off to sunny Hamilton on a rainy afternoon and met with the excellent Malcolm, who runs Hamilton bikes.  Malcolm’s business is refurbishing bikes and fixing silly problems like ours. I was a bit dubious at first when Malcolm suggested, “well we’ll just drill into the frame, then use these cable guides which are really meant for brakes,” but they worked! And although it took us about six hours, Malcolm was always happy to help, teach us and send us for pastry. So our enormous thanks to him for being so generous.</p>
            <p>And our thanks to the top gentleman Dan Jones, and the splendid Helen Blake, for driving all the way from London to help us build our bikes and then driving all the way back again all in 48 hours.</p>
          </AccordionItemPanel>
        </AccordionItem>
      </Accordion>

      <br></br>
      <div><h2>Europe Outbound</h2></div>
      <Accordion allowZeroExpanded>
        <AccordionItem>
          <AccordionItemHeading>
            <AccordionItemButton>
              10/4/2017 Leaving day has finally arrived
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Helen</p>
            <p>We looked around the flat, empty of all our belongings and realised there was no turning back. And we were so glad.</p>
            <p>Leaving day had finally arrived and away we went to meet some of our friends and family at the Bike Station in Glasgow for a final goodbye and a send off. It still felt a bit surreal. Actually leaving. It had been in the planning for over a year but it still always felt like an idea, a non-tangible thing which was spoken about yet never felt like it was getting any closer.</p>
            <p>Even the first three days down to Newcastle for the ferry felt like a short trip away from home, but there now was no home to go back to. Our home for the next 17 months is the marvellous green tent we are yet to nickname.</p>
            <p>Whilst we've done trips away with the bikes and the added weight, cycling with it day after day is taking some getting used to. Day one was a route we've done a dozen times from Glasgow to Edinburgh and we were both a little frustrated at how much slower we are with the heavier bikes and the smaller wheels. But this is a marathon not a sprint, and we have to give ourselves some time to become accustomed to our new way of life. Day one of any trip usually has teething problems and ours appeared in the way of saddle looseness, small mechanical faults and managing eating patterns. It happens. Shouganai.</p>
            <p>Day two started with a beautiful blue sky and a ride through Edinburgh with Bob, Mike's brother, and then further out of the city along the seafront. After lunch at Dunbar, we slowed a little and made it down to Berwick Upon Tweed later than planned so we didn't make it to our intended campsite that night. After one more potential mechanical (which turned out to be nothing at all) I had a mini tantrum and we found a new campsite one mile away.</p>
            <p>Having looked at their website, they claimed they had tent pitches so we lived in hope we could contact a night porter, because by this point it was 7.30pm, to let us have a shower block key and we could bed down for the night. We rang Ken, a wonderful bumbly man, who was worried that he had heard that they weren't accepting tents any longer. However, when he arrived in his car and saw us in our dishevelled state he took pity, said he hadn't heard officially that they weren't taking tents, took a little money off us and pointed us to a bit of grass behind some static caravans. </p>
            <p>Ken you are a wonder, a marvellous, marvellous man.</p>
            <p>Day three, we pushed onwards to get as close to Newcastle as possible. We were to get the overnight ferry from North Shields to IJmuiden the next night and we wanted to stay with Mike's sister the night before. The way out of Berwick Upon Tweed took us along the National Cycle Route 1, and what a shameful state of play that route is. Sustrans really should be ashamed of themselves for accepting that route as a national cycle  path. There wasn't even a path in places, just grass, and at some points ruts worn so deep by cars my front panniers got stuck.</p>
            <p>The moral of the story is, don't trust British national cycle paths. Sometimes they're blooming brilliant, other times they're a disaster.</p>
            <p>evertheless, we carried on but were inevitably slowed down. We got as far as Blyth by 7.30pm and Mike's sister came to collect us for a last farewell before we left the country for over a year. But don't worry, we didn't cheat. We were dropped back in the exact same place the next day for a final 15 miles down to the ferry.</p>
            <p>Our final few days in the UK were difficult but they taught us a lot about what we should expect from the trip ahead. We know to eat more frequently because the bikes drain you so much more than a normal, unweighted road bike. Secondly, we learnt that we ideally need to stop no later than 6pm on a big day. We get far too tired and hungry and we start to get very short tempered. There's no point in getting that way so we should just avoid it when possible. </p>
            <p>But onwards we go, to the continent and on to the real adventure, the unknown...</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/TZ2bUsYHEKI" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionItemHeading>
            <AccordionItemButton>
              13/4/2017 Moving forwards to the continent
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Helen</p>
            <p>The ferry to Ijmuiden (Amsterdam) was fantastic. Neither of us had been on an overnight ferry before but were impressed with the level of comfort we were afforded. On the boarding ramp, we met David, another long distance cyclist on his way to Australia from Ireland and had a drink with him on board and learnt a bit about each other and the nature of the trips we were undertaking. We're hoping to bump into David later down the line in a future country so watch this space. [spoiler alert: we did]</p>
            <p>We had originally planned to cycle north of Ijmuiden and miss out Amsterdam to speed along our journey on to Bremen (where we were to spend my birthday with friends) but changed our minds last minute and went east off the boat to the 'dam. So lucky we did! What a stunner of a city, and built for people on foot and by bike, less so by car. That's how a city should feel. You shouldn't feel alienated and at risk of being hit by a car. That's just my thought.</p>
            <p>Anyway, we stopped for lunch (as disembarking from the ferry took forever since we were the last ones off) and journeyed onwards towards our first night in the Netherlands. We had previously contacted a Warm Showers host over in Hardewijk so had set ourselves a target distance. You can't really wild camp in the Netherlands (there are designated spots but they can be hard to find) so we needed hosts if we weren't to be disrespectful.</p>
            <p>So the Netherlands is flat and all the way through Scotland and England when it had been really hard and muscle damage had caused my thighs to bruise we had been telling ourselves how easy the Netherlands was going to be and it would be a good rest to get used to the bikes. We hadn't accounted for the possibility of general tiredness taking over, a low tyre pressure we didn't notice until the next morning, and the psychological difficulty of long, straight, flat roads. We are very used to hills and undulations causing the scenery to change all the time and the feeling that you're actually getting somewhere. There were some roads in the Netherlands which were so long and flat, it felt like you were cycling on the spot because nothing changed for miles. It was sometimes like a mini Nullabor desert 90 mile straight in Australia, but with less desert. At least it gave us a tiny tiny inkling of what that's going to be like next year…</p>
            <p>Nevertheless, we got to our hosts who were gracious and welcoming. They're a lovely family of three boys, mum and dad and the very excitable pet dog, much to Mike's delight. Thank you so much Anita and Jochim, we had a much needed relaxing, if short, stay with you. And thank you for the air for the tyres!</p>
            <p>The next morning we aimed for a much shorter day - just 30 miles - to let ourselves recover. Scotland and England had been a difficult start with the weight of the bikes to get used to and we just didn't give ourselves any room to settle into a routine. The plan was to find a campsite close to Zwolle, finish early and have a proper relaxing evening. Cycling past 5.30pm had been a bad plan previously as we got far too hungry and tired to really keep going, so we just gave ourselves a break! And that's OK! We found a fantastic campsite with an attached B&B just a few miles out of Zwolle called Boerhoes. I'd go back, it was brilliant. It was basically a farm with a field for camping. So relaxing, so calm; just what we needed. As you showered you realised a section of the barn has been cornered off to create a wash room and the rooster would crow whenever he heard you. Just brilliant.</p>
            <p>This short day gave us two long days to get to Bremen in time for my birthday on the 12th. We both wanted a complete day off on that day as that would mean it had been 8 days of back to back solid cycling and we needed to rest our legs. So onwards we pushed into Germany and stopped at Meppen to look at our options for the night. It is illegal to wild camp in Germany as there were no Warm Showers hosts in the area which we could see were active. However, there was a camp site nearby in a tiny village called Durgen. It was on Google maps and had a review from 9 months ago so we figured it would still be there. The route there took us off road and at one point involved us lifting the bikes over a fence. Once we got to Durgen, the only sign of the camp site was literally a sign on a barn. The website showed a huge field big enough for 100 people and a shower block so we were a bit confused. All we could hear was a German lady shouting at some cows in the barn, but no other signs of life. We rang the doorbell of the house listed on the website as the location, but no answer. We felt like it could've been the start of a horror movie, so I posted a picture to Instagram of the camping sign *just in case* something happened. (We were clearly over tired by this point and our imaginations were running wild). We sat and evaluated our options and decided that we had four:
              <br></br>1. Wild camp in the woods (we were surrounded by woods and probably wouldn't have been seen).
              <br></br>2. Go to the next town and get a B&B.
              <br></br>3. Push on to two towns over where there was an active warm showers host but that would've taken another few hours with no guarantee he'd take us in.
              <br></br>4. Knock on the house one last time and try again.
              <br></br>We knocked. The lady from the barn answered. Mike's not bad at German and asked the lady where the camp site was. She pointed us down a dirt track which we hadn't ventured all the way down and said it was the first thing we would come to. She didn't ever ask for money so we said thank you and went on our merry way. A way down the track we saw signs of a huge field and a shower block. I can't tell you how relieved we were! Tent up, food eaten, pots washed, showers had and we were in to bed to watch a episode of Game of Thrones before falling very quickly to sleep. All we heard all night long was a woodpecker having a good old go at a tree nearby, and a little bit of light wind and rain, but that was it.</p>
            <p>We love camping.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/e3xn_X6rva8" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionItemHeading>
            <AccordionItemButton>
              14/4/2017 Hungry days and standing stones
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Helen</p>
            <p>The morning of the 11th April was grey and cool and overnight Mike had strayed from our learnt keeping-warm technique of sleeping in the sleeping bag silk liner, cover yourself in a cheap Ikea blanket, all enclosed in our sleeping bags. It's unbelievably cozy and does make getting up difficult on such grey, cool days. Mike was cold overnight because he neglected his silk liner AND the blanket. What a sausage.</p>
            <p>We really wanted to get into Bremen to stay with our friends Nina and Rasmus by that evening since the 12th was my birthday and we were hoping for our first full day off. This meant a 135km day - the longest so far.</p>
            <p>The night before we had stopped in the town of Meppen to and bought supplies for our long ride. To be honest, those were mostly chocolate bars, but we also had some delicious German muesli bread rolls  which we ate with bananas and Dutch jam that we bought from a charming little roadside honesty shop (the bakeries here are AMAZING, and cheap, and everywhere).</p>
            <p>We had loaded up on carbs the night before, and with more carbs in our bellies we were ready to hit the road again.  Like previous days we planned our ride on a town to town basis.  This has helped us break the ride up into more mentally manageable chunks, as well as provide useful top up stops.  It turned out Mike was on a hungry day so we needed lots of stops along the way.</p>
            <p>Hungry days are funny things, sometimes one of us will just feel the need to eat almost constantly, and others we will be able to ride with not much more than a normal day's food.  We have learned that Mike must eat at 3pm, whatever the situation, or he'll face a bonking. It's not even so much the energy, but the need to feel something in his stomach that makes eating necessary.</p>
            <p>The ride itself was pleasant enough.  The German cycle ways mostly run alongside main roads, so they are often very direct between towns but not very varied.  Despite that, they are not always in the best condition, and can be very bumpy because of plant roots beneath the tarmac.  Every time we hit a root a jolt would shoot through our wrists and elbows, and we would have to slow right down and speed back up again, which, with heavy bikes can be hard going, even on flat ground. After a few hundred kilometres of these we've been a bit concerned about carpal tunnel syndrome, especially for Mike whose hands were getting very sensitive, but with a bit of a rest those troubles are clearing.</p>
            <p>There were two real, and unexpected highlights to the day. Firstly we had a short detour from the main road and through a beautiful pine forest, which was a real welcome break form the dozens of lorries passing every hour.  Second, as we neared Bremen, Mike noticed a sign for "High Stones" just off the roadway.  Curious, we turned back and down a short bridleway, and there, just tucked away in the woods was a brilliantly preserved neolithic mass tomb, built around 5000 years ago to hold the remains of the dead.  We learned from Nina that there are many of these tombs in the area that she and her friends used to (not terribly respectfully but nevermind) play on.  Nevertheless, we were amazed by the sight and in particular the fact that, after all this time, the capstones were still in place.</p>
            <p>We pedalled on our merry way to Bremen, the last kilometers still passing with ease, where we were met with hugs from Nina, a delicious and much needed dinner of nutritious roasted vegetables, a glass of wine, a hot shower and a very comfortable bed.  And then a long night's sleep. A great day.</p>
            <p>Next up: time in Bremen, and the unpleasant trip to Hamburg (saved by a lovely man called Dennis), and a small change in route.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/8oidL8wJZ9Q" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem >
          <AccordionItemHeading>
            <AccordionItemButton>
              19/4/2017 Weird Weather in Germany
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Helen</p>
            <p>Our first day off was to be for my 28th birthday and it was such luck that we were in Bremen with friends.</p>
            <p>We began with a visit to the sweet shop and a wander around the older part of Bremen. The day only got better with a German sausage for lunch and a relaxing late afternoon chilling back at the flat.</p>
            <p>We had anticipated the next day to Hamburg to be an easy one, but as we had learnt so far, easy days turn out to be the extra difficult ones! Side winds can often be as hard as head winds simply because you're constantly fighting to keep your front wheel straight and not get blown into traffic or off into the verge. The terrain itself was simple; just a few mild undulations. We had welcomed the hills into Bremen two days before but now they felt ridiculously difficult for reasons we couldn't explain. We got to a small town on the outskirts of Hamburg and decided to take the advice of our friends' and avoid cycling directly into Hamburg because it's a city built for cars and navigation is difficult. However, we learnt that public transport can be no better! There was a rail replacement bus service (a term British readers will be most familiar with) and by this point I really needed the toilet but we had to cycle another 6 miles to the next train station to get on *another* train to get to our destination. Once we got there, there was no lift and I had somehow lost my train ticket.</p>
            <p>Maybe we hit this point in Hamburg at the wrong time, maybe it was just the wrong day, or maybe it was the bystander effect. But I was sat in a station in Hamburg almost in tears and we both looked lost because we didn't know whether we could take our bikes to the platform, what to do about tickets, where to go and who to ask, and no one offered any help for about 20 minutes. We just didn't know what to do. Finally, the security guard who had stood near us, staring at us, offered to help put our bikes on the escalator down to the platform and help us on the train. That was allowed, although signs said otherwise.</p>
            <p>Anyway, we got to Hamburg to stay with the lovely Dennis, a friend of our friends from Bremen. He let us into his flat to cook and make ourselves at home and fall asleep whilst he, rightfully, continued to celebrate the Easter weekend at the local pub. I wished we had enough energy to join him!</p>
            <p>We woke up 12 hours later and decided to take an unplanned day off in Hamburg. Unfortunately everything was closed for Good Friday but we had a little wander and then back to the apartment for a Game of Thrones marathon and a completely relaxing and rejuvenating evening. </p>
            <p>Because of the palaver getting into Hamburg, we decided to get a train straight out of the city the next day. We got off of the (double decker) train in Bad Oldesloe and cycled easily up to our next Warm Showers host in Grube. Dear Helge, what a wonderful stay we had with you!</p>
            <p>Our journey to Grube was not without amazing weather. Short, sharp, freezing episodes of hail would wash over the landscape with extremely strong winds. You could see them coming from miles away and they were so brief, sometimes we would just stop in a bus stop to let them pass. I'll never forget one passing storm which has such strong winds our 45KG bikes plus ourselves were blown uphill. We weren't pedalling for a long time, but just kept going uphill. The weather was weird, but fantastic, that day.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/zpWIa11S4X0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem>
          <AccordionItemHeading>
            <AccordionItemButton>
              19/4/2017 Route Change
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Mike</p>
            <p>We were in Copenhagen yesterday enjoying the spring blossom trees and all of a sudden we were asking "is that blossom or snow?"</p>
            <p>It was snow.</p>
            <p>It was such a beautiful and magical moment but it made us realise that it was a cold spring up this way and our journey up to Umea was perhaps a little too early in the year. Even just a couple of weeks later would be better but, coming from Glasgow, we'd rather avoid the cooler weather as much as possible because we’ve totally had enough of it.</p>
            <p>Our new journey is actually way more exciting and we're wondering why we didn't plan it this way in the first place. We'll make our way over to Stockholm and get a ferry to the Åland Islands.</p>
            <p>What's that? What are the Åland Islands? I know, I'd never heard of them either.</p>
            <p>They're a group of islands, an archipelago, in the entrance to the Gulf of Bothnia which belong to Finland but most people speak Swedish. We can island hop our way over to Finland, save ourselves some days which we'll need later on in the trip but not shy away from staying in the cooler climate for a little longer. </p>
            <p>So that's our new plan. It puts up ahead of ourselves by about 2 weeks, but we'll definitely need that buffer when the terrain gets more mountainous or we have to wait for a ferry from Azerbaijan to Kazakhstan so it's certainly not time lost. It also gave us that spare and unplanned day off in Hamburg which we really needed, but without adding stress.</p>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem >
          <AccordionItemHeading>
            <AccordionItemButton>
              22/4/2017 Denmark
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Mike</p>
            <p>Things about Denmark:
              <br></br>It was excellent for cycling in;
              <br></br>Copenhagen was beautiful; and
              <br></br>The weather almost spoiled it all (but didn't).</p>
            <p>Once we left the incredibly helpful Helge, we rode north to catch the ferry from Puttgarden. Not the easiest affair. So to anyone who is reading this and planning on doing the same, just pretend you are a car. Do not follow the cycleway to the terminal - you cannot buy a ticket there. Do not approach the building with a large sign reading "tickets" - you cannot buy a ticket there either. Just get in one of the lines signposted for cars, motorhomes, motorbikes and lorries (note, not signposted for bikes) and get a ticket from the booths.</p>
            <p>The ferry was pretty uneventful, apart from the pangs of homesickness brought on by the large display of whisky on offer, one of which was from our 'local' distillery, Glengoyne.</p>
            <p>Off the ferry we made our way to Maribo, after being stopped by the police at the port. The chap who stopped us gave us directions in perfect English and wished us well. As you would expect a cycleway took us all the way to Maribo where we spent the night. Helen had previously read that there was nothing much between the port and Maribo so thankfully we had already planned for this extra journey onwards.</p>
            <p>We anticipated an easy day two, riding to Copenhagen. The lesson we have learned is never tempt fate by expecting a nice day, just take them as they come.</p>
            <p>A few minutes after setting off we were hit by a huge thump of freezing rain. We were both soaked. Thankfully, the blasting head wind blew the rain through after about 30 minutes, and we just had to contend with that together with the 5 degrees temperature. Then I got a puncture so we got even colder while I fixed that. The positive was that I noticed the puncture right next to a petrol station so the pressure in my tyre from then on was perfect!</p>
            <p>Next up, after a rickety bridge, we had a 50km cycle into Koge where we decided to camp that night. And so it was 50km of cycling into the wind, drenched and along a road that had only three bends in it. Otherwise it was totally straight. We both struggled considerably and variously neither thought we would make the end. I usually perk up when we are within 30 km of the end, because I can imagine actually getting there, but it didn't happen. We rolled into our campsite, ate, slept and set off again for Copenhagen.</p>
            <p>We didn't actually stay in the city. When we were in Bremen, Rasmus called his aunt who offered to put us up for the night in their house in Hillerod. We took the train up there and back to Copenhagen. It was a fantastic night: Lise and Kristen were so friendly, generous and so much fun. Before dinner we went for a walk around the former royal palace in Hillerod, and during dinner we all got very drunk. Lise very kindly attended to our laundry and sent us on our way in the morning with a packed lunch and wine to take with us. Thanks Lise and Kristen!</p>
            <p>And then it was back to Copenhagen to enjoy the city for a couple of hours, walk through the blossoming trees and realise that the petals falling on us was actually snow (see previous blog post). And we were still heading a long way north, but not expecting anything easy to come.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/DJ8SHpCEsDs" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem >
          <AccordionItemHeading>
            <AccordionItemButton>
              28/4/2017 Thar she blows
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Helen</p>
            <p>I never thought I'd be grateful to get back to undulating hills, but it brings with it an ever changing landscape to admire.</p>
            <p>Sweden, so far, is a wonderful mixture of lakes and forests, asphalt roads and gravel tracks. The road infrastructure is extensive for such a sparsely populated country (compared to the road network in, say, Scotland) so we're often travelling for miles along fantastic asphalt roads with barely a couple of cars passing us. So whilst the cycle infrastructure isn't there compared to the intercity cycle tracks in the Netherlands, Denmark or even Germany, the roads are pretty great to travel on.</p>
            <p>The only exception to that rule is when travelling on the blue signed roads which are the UK equivalent of A roads. They’re the roads numbered with double digits (e.g. 17 or 23) and we urge all cyclists to avoid them like the plague. We went on the 23 before we met Iain who advised us otherwise and were very nearly hit by a bus. Mike had to shout at me to bail off the road. We were going up a hill, trying to keep to the right whilst giving ourselves somewhere to bail to (the sage and sad words of Mike Hall). On this uphill, the one lane in our direction turned into two to let cars overtake the many lorries which travelled this road to the next large town. The lorry which came up behind us had seen us and moved into the next lane, but the bus following far too closely behind the lorry hadn’t seen us and it was a very near miss. Generally, the overtakes have been textbook, but that one was terrifying and I had to take a minute off the bike to let my jelly legs go solid again.</p>
            <p>Whilst trying to avoid these double digit roads we're also trying to keep a mixture of the gravel and asphalt roads, predominantly to keep it interesting but also to get some experience on the worse roads we'll have the pleasure of experiencing in future countries. Of course, this led to Mike's punctures (one tiny bit of flint got through in Denmark on the dirt track from the Rodby ferry to the campsite at Maribo, and then another small sharp stone on the gravel tracks in Sweden) but both were patched up and we were on our way again in 10 minutes.</p>
            <p>So we got of the train at Malmo, stopped for long enough for Mike to buy a sticker for his bike and continued on the pretty darn good inter-town cycle path up to Lund for the night. We were recommended Lund by someone on Twitter, so took the chance to both see a beautiful old city and stay with a warm showers host. Seb, thank you for the space on your floor for the night. We both slept very well and enjoyed the little piece of home in the form of bacon and eggs in the morning! Also, thank you for the book to last me until I get a new Kindle in Stockholm.</p>
            <p>We allocated ourselves 10-11 days to get to Stockholm because we knew the hills were coming. We were pleasantly surprised to find that they weren't as steep as we had thought and absolutely loved the gentle undulating hills through forests, taking in the views of pretty cottages and houses along the way. Our endurance and strength is building, without any doubt, and that only adds to our confidence. The only real difficulty to contend with has been the wind. That's growing in strength too!</p>
            <p>Sweden has been the first country we've visited (except Scotland) where wild camping is legal so we took the opportunity just outside of Hassleholm. Apparently everybody is nervous on their first night wild camping: have you picked the right spot? Is anyone going to catch you? If they do, will they care? Are you accidentally on someone's land? We made sure we were out of sight from the few houses around the spot we chose and had a mightily cosy night sleep out of the wind.</p>
            <p>We were positively blown sideways up to Almhult where we met with the ever helpful Iain; a Scotsman in Sweden and a warm showers host. Unfortunately he had building works going on so couldn't host us but took us out for pizza anyway since we ended up camping in the town. He also took us back to his house to give us a GPX route of the best riding up to Stockholm which we could input to Mike's phone and use as a turn by turn GPS. Bloody marvellous! Thank you so much Iain.</p>
            <p>Almhult is also the home of Ikea. The man who founded it was born there, the first outlet was started there and the headquarters are now there with a huge distribution plant taking up a large portion of the industrial estate on the outskirts of the town. Most of the people living in Almhult work for Ikea. The original building of the first shop is now an Ikea museum, which I kind of wish we had had time to visit! </p>
            <p>We were then blown east towards Linneryd.  The weather has been very changeable, and apparently very cold or this time of year, so we may even have some snowfall tonight. Even in Almhult we woke up to ice on the tent. Tomorrow we will turn into a bit of a headwind which isn't due to give out until Stockholm. I'm trying to tell myself to enjoy this cold weather because there'll be points in future countries where we'll be so hot we'll wish we were back in this temperature again.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/o2ARkr2zMUo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <br></br>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/AIHDzWrK2Bo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem >
          <AccordionItemHeading>
            <AccordionItemButton>
              1/5/2017 Winter is coming, again, in Sweden
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Mike</p>
            <p>"You're the first Scottish people we've had in 22 years! I love Scotland. You must stay for dinner"</p>
            <p>These are the words that greeted us when we sat down at the campsite at Linneryd to have our dinner. Andy and his wife are a couple from Germany who have operated campsites in Sweden for the past two decades. He has toured Scotland on his motorbike with his friends twice and absolutely loved it there. He said that the Scottish people were so friendly and helpful and that since we were from Scotland he must repay the kindness. So after our spaghetti bolognese, Andy cooked us cordon bleu. A two dinner night, win! He gave us as much red wine as we could drink as we were so tired and let us camp right on the beautiful lake shore of the campsite.</p>
            <p>The weather was set to change with snow lying next morning so we decided to take the next day off and spend it relaxing in the campsite. When we woke, we were greeted with beautiful sunshine, a mirror lake and no hint of bad weather to come but we had slept so well that it was too late to pack up. And so we stayed an extra night. I spent a few hours catching up on my journal while Helen wrote the last blog post. Andy, meanwhile, while complaining of the bad weather that hadn't yet arrived insisted he had nothing to do and so he would instead teach us the tradition Viking game of Kubb.</p>
            <p>We weren't very good at it! Andy won the first game easily, went so easy on the second that his confidence eventually made him lose and I played him for the title. Scotland vs Germany in round three. This necessitated me putting on my glasses and Andy providing beers and Scotland was victorious! </p>
            <p>As soon as it was over, the weather arrived late and it was shortly bouncing hailstones and we were glad to have stayed. We spent the following night in one of the small lakeside cabins with heating and a proper bed and were ready to go again the next morning.</p>
            <p>The delayed weather continued into the next day and became substantially worse.</p>
            <p>From the campground we rode north 75 miles, 3000 feet of climbing, in icy rain and snow, into a headwind. The thought that kept us going was that we were headed to another warm showers host, Janne and his girlfriend Xian. By the time we arrived my feet were cadaverous, Helen's too, and tremendously painful. We were cold, tired and soaked. The day was saved by the sight of a wild moose crossing in front of us (a few miles before the Elk Park where we stopped for coffee). We decided that the only verb that could describe a moose's walk was "to gangle" and Helen does a marvellous impression.</p>
            <p>Janne is tremendously well travelled in Asia and gave us a lot of advice on what to see and how to travel while in the 'Stans and in China. He insisted that we ought not miss the beautiful green hills of Kyrgyzstan or the Tian Shan mountains in western China (which were currently not on our route). He also insisted that a ride from Urumqi to Xi'an would hold little more than 2000km of desert, motorways, trucks and gravel and would be better served with a train so we could later ride through the Tibetan foothills. We may well be taking this advice and it is very much appreciated so thank you Janne. </p>
            <p>With sore legs we pressed further on northwards following Iain's route but didn't make our target of Bjorkfors. Instead, we stopped a few miles south in the town of Horn where we tried our luck in a hostel. When we arrived it was entirely vacant, only the keys were left in the office door and no knocks on any doors were answered. Having ridden again that day in the snow we did the only thing that we could; let ourselves into the office and waited for two startled owners to reappear to the sight of two bedraggled cyclists making themselves at home in their place of business. </p>
            <p>The distance to Bjorkfors wasn't the problem. It was the resurfacing of roads which otherwise should've been tarmaced. We rode on difficult gravel for about 10km which slowed us down, as well as hitting some very steep hills which we hadn't expected. On top of all that, again there was a headwind and again we were soaked through with snow which melted through our clothes. Helen struggled, particularly given that this was a day where she was scheduled not to take her Citalopram and on a particularly difficult uphill, after a heavy hailstorm, we took some time out at the side of the road to take a moment to rationalise where we were and what we were doing. All of that said, the hostel owners were great, gave us a lovely room and we had free run of a beautiful former hotel for the night with only one other guest. </p>
            <p>Northwards again and we rode to a warm showers host - Ben and Rebecca Hell. Again, two Germans who had made new lives in Sweden where Rebecca makes and sells the most stunning children's woollen clothes and adorable shoes. The weather had improved, although snow and a headwind were still present. This time the big delay was in the roads, again. The Swedish gravel roads are usually hard packed, smooth and very easy to ride on but our route took us down a track which had recently been resurfaced and left to be compressed by traffic. It was as if we were riding along a beach. After a kilometre and waving a passing car down for advice on the route, we had to turn back. This meant a detour and another recently resurfaced track but this time slightly more worn, so passable. Although Ben and Rebecca suggested we really should stay for two nights, we decided to press on in the morning after I had made friends with a large black llama who enjoyed sniffing my face. His white companion remained unconvinced. </p>
            <p>Our intention was to ride beyond Nykoping which meant getting a ferry and would've put us in easy reach of Stockholm by Friday night. Unfortunately, when we arrived at the ferry crossing, the ferry was cancelled for maintenance and not scheduled to start again til the next day. Instead of making a long detour we instead chose to camp by the nearby beach, have an early finish, a bonfire and two hot meals. The ferry resumed much later that evening, but by that time we had settled and decided to stay put.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/9Ts7WPifolk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
            <p>Waking in the morning, we quickly packed in our fastest time yet and set off for an early sailing. As we had done with some other large cities, we decided to ride to a suburb of Stockholm and take the train the rest of the way. We have found big cities to be hard to navigate, and liable to take many hours. So until we get used to all other aspects of the trip and don't have this option, we may well still take the train into the city centre where we can. Having made our target of arriving in Stockholm, we decided to have an extra day off. Helen's knees were becoming increasingly sore as were my wrists, elbows and thighs. With this in mind, we booked ourselves in for a sports massage on Saturday morning with an enormous yet softly spoken man called Jimmy. The pain, and results, were tremendous. We spent our two nights in Stockholm with Helen's old flatmate, Jess, her boyfriend Liam and their two very vocal and inquisitive bengal mix cats. Helen tells me that every time I meet a cat I preface that liking of that particular cat with, "I don't usually like cats, but…" and this applies to all cats. Maybe I do like cats, at least a bit.</p>
            <p>We are now, somewhat inadvertently, on a party boat. Some may call it a booze cruise. We are in a not so sumptuous cabin beneath the car deck. Our fellow passengers sound like they're enjoying themselves immensely but we're ready for bed and looking forward to what Finland brings us in the next few days at the end of leg one, northern Europe.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/HqhcZS0X6wU" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem >
          <AccordionItemHeading>
            <AccordionItemButton>
              7/5/2017 Saving and spending money in Finland
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Helen</p>
            <p>Finland properly began our wild camping time on this trip. This wasn't because of the lack of being able to do it in Sweden - there were plenty of places we could've camped and it is legal - but because the weather warmed up and our feet were no longer like ice at the end of the day.</p>
            <p>The ferry to the Åland Islands was loud. It was a party boat. We took the boat on the eve of May Day so we asked for it, really. A couple of episodes of Game of Thrones and we were set for bed but alas, sleep was difficult to come by.</p>
            <p>Nevertheless, we made it a great first day in Finland (if the autonomous and demilitarised Åland Islands counts as Finland, because it technically is, but isn't) and got all the way to our ferry terminal three hours in advance of the boat because the islands are so small. Being May Day, the office wasn't open and it was very quiet so it took us a few asks of a few boat men to establish that, yes, there would be a boat leaving to go to Galtby at 4pm that day and yes, it was the boat which was waiting in the harbour.</p>
            <p>We took the opportunity to have a snooze on the dock in the sunshine since it was the first real sunshine we'd encountered since… well… the Netherlands…</p>
            <p>We got to Galtby at 9pm - that's a five hour ferry ride between islands! But it brought us to the start of what is kind of mainland Finland. We only needed two more small RORO (roll on roll off) car ferries and a load of bridges to get us to Helsinki. The sun was starting to set, so we quickly ventured into the woods which were right next to the ferry port and found the perfect spot to wild camp with the most f***ing fantastic sunset to sit and watch, completely in awe of the world and the universe.</p>
            <p>We took three more days to get to Helsinki and we wild camped the entire way. Yes, we probably smelt quite funky but we had the best, and cheapest time. But Finland is damn expensive. We knew this, we expected this, but the reality of it is quite impressive. A coffee in Finland was about 4 euro, if not more. I can quote Mike as saying, "It's like, y'know, cray cray exponseeve". I think the long days are getting to him.</p>
            <p>While Sweden was a brilliant training ground to get used to the weight of the bikes and going up slow inclined hills, Finland was a test of our endurance up steeper hills. I felt like it was Devon or Cornwall on steroids. The hills are steeper and shorter and you really have to be careful not to hurt your knees. It's easy to be in a high gear (low cadence) on the flat and approach a steep hill and not shift down enough to a low gear to spin your way up the hill. It's easy to be in the wrong gear since you think that the hill is short, but you lose too much momentum up said hills to make that gear worth it. Grinding up hills repeatedly will ruin your knees. Change down your gears.</p>
            <p>We rolled in (on a quick commuter train) to Helsinki late and had already booked two beds in a hostel dorm room right in the centre so we could easily get the ferry the next day to cheaper-land - sorry, Estonia aka the rest of the world and their normal prices.</p>
            <p>Beyond the expense, Helsinki is a lovely city - we can't say more than that because it was too expensive for us to do much other than wander around and find Mike a sticker for his bike, sit in the park and sit in a coffee shop stretching one drink over a few hours. We'll certainly go back, but only once we have more disposable income.</p>
            <p>So getting the overnight ferry to Tallinn marked the end of leg one. One month into the trip! One month on the road.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/fgWrkF6VeOk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
        <AccordionItem >
          <AccordionItemHeading>
            <AccordionItemButton>
              13/5/2017 Automobile intimidation in Estonia
            </AccordionItemButton>
          </AccordionItemHeading>
          <AccordionItemPanel>
            <p>Author: Mike</p>
            <p>We were told by various people we encountered about what we might experience after crossing from Helsinki and entering the Baltic States. One of our warm showers hosts in Sweden, Rebecca, had said that although Baltic Estonia was trying very hard to become culturally more Scandinavian. Latvia, on the other hand, retained a more Russian identity. It was interesting to see how this translated to attitudes towards cycling in particular. </p>
            <p>We had a slightly odd beginning to our time in Tallinn when we were approached by a clearly drunk Estonian man and his Russian companion who had been watching us gawk in the main square. Intrigued by our bikes, they approached and asked where we were from. As soon as we responded "Scotland", we were thrown deep into a political lecture on cultural identity, language and independence (we were more berated than we were lectured). After making our excuses to this gentleman and disappearing with nowhere in particular to go, we found a place for coffee and took ourselves back to the main square to look at our route of the city. There, we met a bike tourer called Maxi who was riding from Poland to Nordcap. He had just ridden through the Baltic States so donated us his paper map and as much advice as he could manage on the route. We had already heard that many of the roads in Estonia would be gravel and we knew from experience in Scandinavia that this would slow us down rather a lot, so on Maxi's advice we settled for a route on minor and major asphalted roads.</p>
            <p>Cycling out of Tallinn was extremely straight forward; bike lines all the way out of the city until we reached the Green Way, a tourist route through the country that incorporated a very long two lane bike path through northern Estonia. Despite not having left Tallinn until noon, we still made our target 100km because Estonia is incredibly flat. Cycling on good asphalt bike lanes and all the time with good overtakes from Estonian drivers. On all but one occasion they would use the entire width of the road to overtake and other than that one close pass we didn't feel in any danger. </p>
            <p>Toward the end of the day we turned down a gravel track to where we had expected a camp site. It turned out only to be a picnic spot by a small lake (which was very, very full of frogs) but it did us for the night as a wild camp.</p>
            <p>There aren't a great deal of shops in or among the small towns in Estonia, and by the next morning we were very low on water. After a few miles we joined the main road and caught sight of an elderly couple gardening. Without us speaking a word in common other than the older gentleman knowing a few numbers in English, we managed to ask for water, which he kindly gave us and also he gave us some advice on our proposed route toward the Latvian border "too gravelly". With this in mind and our experience on the Estonian roads so far and our advice from Maxi, we felt pretty comfortable changing our route to ride on the major highway running from Riga to Tallinn. As with our experience on the previous day, despite it being a very heavily trafficked route, we never felt particularly vulnerable, even during a long section of road works over which we had to push the bikes.</p>
            <p>Helen and I have a finely tuned technique for dealing with roads with heavy traffic and in particular those which carry a lot of articulated lorries. Helen rides in front while I ride closely behind concentrating mostly on the view in my mirror. We ride at a steady rate and if I see anything in the mirror such as a truck or car that looks as if it won't be giving us enough space (keeping in mind the oncoming traffic) I will call to Helen to come off the road and wait until I call that it's clear to carry on. In this way, we've managed to keep ourselves safe, and have avoided at least one possible collision. </p>
            <p>We had our final camp by the sea near the border with Latvia. Our next possible seaside camp will be in Turkey and it's something we've got used to and will miss.</p>
            <p>The next day we set out for Riga, about 145 km away. That's a big distance for us to cover in a day but we felt that we'd be able to with the flat topography and the wind slightly behind us. Based on our experience with drivers so far we felt fairly comfortable in continuing down the main route to Riga, which incidentally was advertised as the EuroVelo 13. </p>
            <p>It was a more challenging ride than we expected. Shortly after crossing the Latvian border we noticed a marked difference in the care of driving; more often than not we would be passed closely and at speed even with traffic heading in the opposite direction. On some occasions one vehicle would overtake another that was already in the process of overtaking us. To begin with this was tolerable but really very stressful and mentally exhausting. The road varied from having a 18 inch wide shoulder with 2 - 3 feet of gravel at the side, to an even narrower shoulder without gravel, and then to a road with a particularly European half slow traffic/overtaking lane. The half lane is kind of a cross between a slow vehicle lane and hard shoulder. For the most part it is used by large vehicles and allows faster vehicles a line of sight past them so they can overtake. There is no hard shoulder beyond the half lane so it was the only place we could ride. And this was on the EuroVelo 13. The half lane meant that very often we were closely overtaken by the vehicles who would ordinarily use it. These passes were made worse when faster vehicles were overtaking slower vehicles which were overtaking us. Other terrifying occasions were when cars were overtaking others whilst coming towards us. Essentially we were being driven at at 100 mph. On one particularly inspired occasion, thankfully far enough away to not bother us, a car overtook a lorry which was overtaking another lorry at high speed with inches between. Fun times! </p>
            <p>We took a short turn off the highway and onto another cycle route which turned out to be thoroughly uncyclable as it was soft sand. After I'd fallen off the bike and we'd been pushing for 30 minutes we resigned ourselves to going back to the highway.</p>
            <p>So after about 60 km of highway riding we were able to turn off and join a coast road. Dreading the prospect of rejoining the highway with traffic building in rush hour and remembering that we needed to get to Riga to get a new bike lock, we decided to take the train for the last few miles into Riga. </p>
            <p>At this point, we thought our tribulations were over, but they'd hardly begun. We'd booked into a hotel on the northwest side of the city, 16km away from the central station so there was still more riding to do. The city centre has, like Glasgow, a motorway running through the centre which we needed to cross, but without the help of any bike suitable crossings. On our first attempt having crossed three lanes of traffic and a double tram line, with three more to go we tried to cross in a gap. We misjudged it and had to retreat to our island but in the confusion my bike fell, trapping my leg and nearly knocking me into the traffic. So we gave up on that. Instead we joined the traffic and cycle as far as we could but after 20 metres, my front pannier was hanging off following the fall and we had to stop. Shortly after we needed to cross a bridge, the only problem being that the lifts were broken so we had to push our bikes up three flights of stairs. With that over, we just had to get to the hotel about 14 km further.</p>
            <p>We rode northwest on a small but extremely busy road. We hadn't anticipated that it would be as bad as it was. The road surface was terrible, there was no bike lane, the roads that appeared on the map to run parallel were sand or mud tracks that were uncyclable and the roads appearing on the opposite side were in fact a derelict allotment site. With little verges or curbs to the side of the road and the eagerness of the Latvian drivers, lorry drivers and buses included, to overtake us even in the face of oncoming traffic our tried and tested system failed. About half way the stress had gotten to us both and we were getting desperate. The fear had taken Helen to tears and we pulled into the upcoming bus stop. </p>
            <p>At that point, after deciding that we couldn't cycle any further we resolved to hitch the rest of the way there. Helen then remembered reading that it was possible to take bikes onto buses if there's space to do so and salvation arrived in the form of a mustachioed bus driver in his bendy bus bearing EU flags. We flagged him down and Helen tried to explain that we needed to get on as it was too dangerous to continue on the bikes. I'm not sure he understood but he waved us on and finally for the first time that day we felt safe on our journey. Ten minutes later we were disembarking and at our 19 Euros a night hotel and spa, in the exclusively Russian speaking district we found ourselves in. With a gruelling day and end, we decided to take the next day off, try and unwind and plan a way back out of Riga and towards Lithuania where we expect the terrible driving won’t improve.</p>
            <p>So for Eastern Europe we have a new policy of avoiding big cities and with them any interconnecting major roads. It might slow us down a little but keep us safe and hopefully we'll be a little more free to enjoy the countries we pass through.</p>
            <iframe width="560" height="315" src="https://www.youtube.com/embed/QX-9iSq9-4I" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
          </AccordionItemPanel>
        </AccordionItem>
      </Accordion>
      <div><h2>More blog posts and pictures incoming...</h2></div>
    </div>
  )
}

export default RTWBlog



//   <AccordionItem >
// <AccordionItemHeading>
// <AccordionItemButton>
//   6/7/2016 
// </AccordionItemButton>
// </AccordionItemHeading>
// <AccordionItemPanel>
// <p></p>
// <p></p>
// </AccordionItemPanel>
// </AccordionItem>